### ISSUE TITLE
How to calculate the domain and the range of tan (abs (x))?

### ISSUE THREAD

**Issue by zuojj** [clux/wolfram-alpha#7]
I want to use javascript draw a function graph,  but I do not know how to calculate the domain and the range of tan (abs (x)) ?    [wolfram](http://www.wolframalpha.com/input/?i=tan(abs(x)))

**Comment by clux** [comment]
I had missed this, but It's not really relevant for this repo anyway. Hopefully wikipedia or some other resource helped you out.
